name: whymighta-dev

services:
  whymighta:
    container_name: whymighta
    build: .
    restart: unless-stopped
    networks:
      - local-services
    deploy:
      resources:
        limits:
          memory: 256m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    env_file: .env

networks:
  local-services:
    external: true