services:
  whymighta:
    container_name: whymighta
    build: .
    restart: always
    networks:
      - local-infra
    deploy:
      resources:
        limits:
          memory: 256m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    env_file: .env

networks:
  local-infra:
    external: true